module.exports = [
  { match: 'WM SLEE', category: 'rent' },
  { match: 'CHTEPINE', category: 'food' },
  { match: 'A TYURIN', category: 'savings' },
  { match: 'A BURTSEV', category: 'food' },
  { match: 'A YULDOSHEV', category: 'food' },
  { match: 'Ionov, Maxim', category: 'food' },

  { match: 'ING SCHIPHOL PLAZ', category: 'cash' },
  { match: 'QUICK 747', category: 'food' },
  { match: 'PostNL AMSTERDAM', category: 'home' },
  { match: 'AANKOMST SCHIPHOL PLAZA', category: 'cash' },
  { match: 'CCV CAMEEL BV', category: 'food' },
  { match: 'NSC AMS', category: 'entertaiment' },
  { match: 'VERTREK 2/LOUNGE 2 2ET', category: 'food' },
  { match: 'OV-CHIPKAART', category: 'transport' },
  { match: 'BAR PITA AMSTERDAM', category: 'food' },
  { match: 'Hoppy Days', category: 'food' },
  { match: 'VIJZELSTRAAT BY TE A', category: 'food' },
  { match: 'DOV MELO', category: 'food', name: 'Wok To Walk' },
  { match: 'Vof Blaauwhooft', category: 'food' },
  { match: 'PizzabakkersOvertoom', category: 'food' },
  { match: 'VAN T SPIT', category: 'food' },
  { match: 'THE BREAKFAST CLUB', category: 'food' },
  { match: 'FIER', category: 'food' },
  { match: 'DE BRAKKE GROND', category: 'food', name: 'Bar Jones' },
  { match: 'Jamin Amsterdam', category: 'food' },
  { match: 'Le Big Fish', category: 'food' },
  { match: 'Jabugo bar Iberico', category: 'food' },
  { match: 'SALOMON LUNCH', category: 'food', name: 'Bagels and Beans' },
  { match: 'Fou Fow ramen', category: 'food' },
  { match: 'Delicatesse Shilla', category: 'food' },
  { match: 'Hong Kong Superstore', category: 'food' },
  { match: 'MOOK PANCAKES', category: 'food' },
  { match: 'THE BUTCHER', category: 'food' },
  { match: 'CALIFORNIA BURRITO', category: 'food' },
  { match: 'Kam Yin', category: 'food' },
  { match: 'BeerTemple', category: 'food' },
  { match: 'PHO VIET', category: 'food' },
  { match: 'MENEER TEMAKI', category: 'food' },
  { match: 'The Rough Kitchen', category: 'food' },
  { match: 'Noodlebar', category: 'food' },
  { match: 'VITAMINSTORE', category: 'food '},
  { match: 'BAR BROUW', category: 'food' },
  { match: 'Julias', category: 'food' },
  { match: 'Terrasmus', category: 'food' },
  { match: 'CANNIBALE', category: 'food' },
  { match: 'DOMINOS', category: 'food' },
  { match: 'UNIQLO', category: 'clothes' },
  { match: 'Bakkerswinkel', category: 'food' },
  { match: 'Praxis', category: 'home' },
  { match: 'Praellokaal', category: 'food' },
  { match: 'Dim Sum Court', category: 'food' },
  { match: 'URBAN OUTFITTERS', category: 'clothes' },
  { match: 'ESPRIT', category: 'clothes' },
  { match: 'DONER COMPANY', category: 'food' },
  { match: 'Doner Plaza', category: 'food' },
  { match: 'Greenbrothers', category: 'food' },
  { match: 'Albert Heijn', category: 'groceries' },
  { match: 'FOODHALLEN', category: 'food' },
  { match: 'Marqt', category: 'groceries' },
  { match: 'Zilveren Kruis', category: 'insurance' },
  { match: 'Good Fortune', category: 'food' },
  { match: 'Asian Kitchen', category: 'food' },
  { match: 'NS Station Schiphol', category: 'transport' },
  { match: 'Radijs', category: 'food' },
  { match: 'VAN DE BUURT', category: 'food' },
  { match: 'Wagamama', category: 'food' },
  { match: 'SALSA SHOP', category: 'food' },
  { match: 'de Doelen', category: 'food' },
  { match: 'The Coffee Company', category: 'food' },
  { match: 'CoffeeCompany', category: 'food' },
  { match: 'STARBUCKS', category: 'food' },
  { match: 'Starbuc', category: 'food' },
  { match: 'DAM APOTHEEK', category: 'drugs' },
  { match: 'cafe Katoen', category: 'food' },
  { match: 'Wok To Go', category: 'food' },
  { match: 'Sterk Delicatessen', category: 'groceries' },
  { match: 'Portare Via', category: 'food' },
  { match: 'MAOZ FALAFAL', category: 'food' },
  { match: 'MAOZ FALAFEL', category: 'food' },
  { match: 'HEMA', category: 'home' },
  { match: /^NS(-|\s)/, category: 'transport' },
  { match: /GVB/, category: 'transport' },
  { match: 'PERRY SPORT', category: 'sport' },
  { match: 'DeOudeDoelen', category: 'food' },
  { match: 'Moeders', category: 'food' },
  { match: 'ABRAXAS', category: 'weed' },
  { match: 'DIRK', category: 'groceries' },
  { match: 'bol.com', category: 'shopping' },
  { match: 'Onitjuka Tiger', category: 'clothes' },
  { match: 'Stedelijk Museum', category: 'museum' },
  { match: 'TOPROW ROEICENTRA', category: 'sports' },
  { match: 'Cut by Mario', category: 'haircut' },
  { match: 'RAMEN YA', category: 'food' },
  { match: 'Eat Mode', category: 'food' },
  { match: 'Pathe', category: 'movies' },
  { match: 'BURGERMEESTER', category: 'food' },
  { match: 'BURGER BAR', category: 'food' },
  { match: 'NES CAFE', category: 'food' },
  { match: 'Bagels & Beans', category: 'food' },
  { match: 'BAGELS AND BEANS', category: 'food' },
  { match: 'BAGELS EN BEANS', category: 'food' },
  { match: 'Decathlon Arena', category: 'sports' },
  { match: 'DecathlonNetherlands', category: 'sports' },
  { match: 'BIRD THAIS REST', category: 'food' },
  { match: 'EYE FILMINSTITUUT', category: 'movies' },
  { match: 'Kriterion', category: 'movies' },
  { match: 'Kohinoor', category: 'food' },
  { match: 'Booking.com BV', category: 'salary' },
  { match: 'Elsevier BV', category: 'salary' },
  { match: 'ELSEVIER AFDBETALING', category: 'salary' },
  { match: 'Winkel 43', category: 'food' },
  { match: 'BURGERZAKEN', category: 'food' },
  { match: 'INT CARD SERVICES', category: 'credit' },
  { match: 'Mata Hari', category: 'food' },
  { match: 'Cafe de Jaren', category: 'food' },
  { match: 'Latei', category: 'food' },
  { match: 'Cafe De Raedt', category: 'food' },
  { match: 'AH to go', category: 'groceries' },
  { match: 'Blokker', category: 'home' },
  { match: 'Van Gogh Museum', category: 'museum' },
  { match: 'Bijenkorf', category: 'shopping' },
  { match: 'BRUG 34', category: 'food' },
  { match: 'Hummbar', category: 'food' },
  { match: 'BURGERIJ', category: 'food' },
  { match: 'Spar City', category: 'groceries' },
  { match: 'Grand Cafe de Balie', category: 'food' },
  { match: /cafe/i, category: 'food' },
  { match: 'VESTA PAYMENT SOLUTIONS', category: 'mobile' },
  { match: 'T-Mobile', category: 'mobile' },
  { match: 'Buckaroo Stichting Derde', category: 'charity' },
  { match: 'Soup en Zo', category: 'food' },
  { match: 'Bar Moustache', category: 'food' },
  { match: 'Gollem', category: 'food' },
  { match: 'AMERICAN BOOK CENTER', category: 'books' },
  { match: 'Gasthuijs', category: 'food' },
  { match: 'La Place', category: 'food' },
  { match: 'OMELEGG', category: 'food' },
  { match: 'Paradiso', category: 'concerts' },
  { match: 'Ysbreker', category: 'food' },
  { match: /^Febo/, category: 'food' },
  { match: 'GlobalCollect', category: 'travel' },
  { match: 'Global Collect BV', category: 'travel' },
  { match: 'A Space Oddity', category: 'entertaiment' },
  { match: 'Stichting Derdengelden', category: 'sports' },
  { match: 'O mai Amsterdam', category: 'food' },
  { match: 'Venkel', category: 'food' },
  { match: 'Blos Horeca', category: 'food' },
  { match: 'OUDE ZIJDS HORECA', category: 'food' },
  { match: 'De Haven', category: 'food' },
  { match: 'McDonald', category: 'food' },
  { match: 'MC DONALDS', category: 'food' },
  { match: 'OPLADENOV', category: 'transport' },
  { match: 'MM Amsterdam Centrum', category: 'entertaiment' },
  { match: 'pizzeria', category: 'food' },
  { match: 'etos', category: 'home' },
  { match: 'Nassau', category: 'food' },
  { match: 'Stach', category: 'groceries' },
  { match: 'UTRECHTSESTRAAT 13', category: 'cash' },
  { match: 'Bever', category: 'clothes' },
  { match: 'STG ADYEN', category: 'travel' },
  { match: 'Adyen', category: 'travel' },
  { match: 'Kroes Advocaten Immigrat', category: 'home' },
  { match: 'motel', category: 'travel' },
  { match: 'Happy italy', category: 'food' },
  { match: 'Volendammer Vishande', category: 'food' },
  { match: 'HEEREN', category: 'food' },
  { match: 'BK 13462', category: 'food', name: 'Burger King' },
  { match: 'TAVERNA BARCELONA', category: 'food' },
  { match: 'ING BANK', category: 'cash' },
  { match: 'JAN VAN GALENSTR 86', category: 'cash' },
  { match: 'Prime Cuts BV', category: 'food', note: 'burgers' },
  { match: 'Greenwoods', category: 'food' },
  { match: 'Frozz B.V', category: 'food' },
  { match: 'YOGEN FRUZ', category: 'food' },
  { match: 'Storm B.V. ZANDVOORT', category: 'food' },
  { match: 'DIESEL STORE', category: 'clothes' },
  { match: 'GREEN BUDGET BIKES', category: 'home' },
  { match: 'BELASTINGDIENST', category: 'services' },
  { match: 'EXPERCASH GmbH', category: 'tickets' },
  { match: 'HavenrestaurantTexel', category: 'food' },
  { match: 'Fietsverhuur', category: 'transport' },
  { match: 'Teddy`s Grill', category: 'food' },
  { match: 'Kruidvat', category: 'home' },
  { match: 'NEW YORK PIZZA', category: 'food' },
  { match: 'JODENBREESTRAAT 96', category: 'cash' },
  { match: 'ZUCCA LEIDEN', category: 'food' },
  { match: 'EAZIE', category: 'food' },
  { match: 'THE DUTCH CO', category: 'food' },
  { match: /BRASSERIE/i, category: 'food' },
  { match: /horeca/i, category: 'food' }, // https://en.wikipedia.org/wiki/Horeca
  { match: /RESTAURANT/i, category: 'food' },
  { match: 'Corner Admiraal', category: 'food', note: 'near' },
  { match: 'Rembr van gogh', category: 'museum' },
  { match: 'Zhu Lin VOF', category: 'food', name: 'Wannemakers!' },
  { match: 'ROEST', category: 'food' },
  { match: 'ING AMSTERDAM', category: 'cash' },
  { match: 'HMSHOST AMSTERDAM SCHI', category: 'food' },
  { match: 'SPARKASSE ERDING-DORFE', category: 'shit' },
  { match: 'Avondwinkel', category: 'groceries' },
  { match: 'Squash City', category: 'sports' },
  { match: 'BGN WEST BV', category: 'food', name: 'Cafe De Klos' },
  { match: 'Reed Elsevier A\'dam', category: 'food', name: 'Elsevier Cafe' },
  { match: 'Hutten Business', category: 'food', name: 'Hutten Business' },
  { match: 'CCV WOK DAMSTRAAT', category: 'food', name: 'Wok To Walk Dam' },
  { match: 'Lucky House', category: 'food', name: 'Lucky House' },
  { match: 'Reisbkh.Pied a Terre', category: 'home' },
];
