module.exports = [
  { match: 'WM SLEE', category: 'rent' },
  { match: 'CHTEPINE', category: 'food' },
  { match: 'A TYURIN', category: 'savings' },

  { match: 'Albert Heijn', category: 'groceries' },
  { match: 'Marqt', category: 'groceries' },
  { match: 'Zilveren Kruis', category: 'insurance' },
  { match: 'Good Fortune', category: 'food' },
  { match: 'Asian Kitchen', category: 'food' },
  { match: 'NS Station Schiphol', category: 'transport' },
  { match: 'Radijs', category: 'food' },
  { match: 'VAN DE BUURT', category: 'food' },
  { match: 'Wagamama', category: 'food' },
  { match: 'SALSA SHOP', category: 'food' },
  { match: 'de Doelen', category: 'food' },
  { match: 'The Coffee Company', category: 'food' },
  { match: 'CoffeeCompany', category: 'food' },
  { match: 'STARBUCKS', category: 'food' },
  { match: 'Starbuc', category: 'food' },
  { match: 'DAM APOTHEEK', category: 'drugs' },
  { match: 'cafe Katoen', category: 'food' },
  { match: 'Wok To Go', category: 'food' },
  { match: 'Sterk Delicatessen', category: 'groceries' },
  { match: 'Portare Via', category: 'food' },
  { match: 'MAOZ FALAFAL', category: 'food' },
  { match: 'MAOZ FALAFEL', category: 'food' },
  { match: 'HEMA', category: 'home' },
  { match: /^NS(-|\s)/, category: 'transport' },
  { match: /GVB/, category: 'transport' },
  { match: 'PERRY SPORT', category: 'sport' },
  { match: 'DeOudeDoelen', category: 'food' },
  { match: 'Moeders', category: 'food' },
  { match: 'ABRAXAS', category: 'weed' },
  { match: 'DIRK', category: 'groceries' },
  { match: 'bol.com', category: 'shopping' },
  { match: 'Onitjuka Tiger', category: 'clothes' },
  { match: 'Stedelijk Museum', category: 'museum' },
  { match: 'TOPROW ROEICENTRA', category: 'sports' },
  { match: 'Cut by Mario', category: 'haircut' },
  { match: 'RAMEN YA', category: 'food' },
  { match: 'Eat Mode', category: 'food' },
  { match: 'Pathe', category: 'movies' },
  { match: 'BURGERMEESTER', category: 'food' },
  { match: 'BURGER BAR', category: 'food' },
  { match: 'NES CAFE', category: 'food' },
  { match: 'Bagels & Beans', category: 'food' },
  { match: 'BAGELS AND BEANS', category: 'food' },
  { match: 'Decathlon Arena', category: 'sports' },
  { match: 'DecathlonNetherlands', category: 'sports' },
  { match: 'BIRD THAIS REST', category: 'food' },
  { match: 'EYE FILMINSTITUUT', category: 'movies' },
  { match: 'Kohinoor', category: 'food' },
  { match: 'Booking.com BV', category: 'salary' },
  { match: 'Winkel 43', category: 'food' },
  { match: 'BURGERZAKEN', category: 'food' },
  { match: 'INT CARD SERVICES', category: 'credit' },
  { match: 'Mata Hari', category: 'food' },
  { match: 'Cafe de Jaren', category: 'food' },
  { match: 'Latei', category: 'food' },
  { match: 'Cafe De Raedt', category: 'food' },
  { match: 'AH to go', category: 'groceries' },
  { match: 'Blokker', category: 'home' },
  { match: 'Van Gogh Museum', category: 'museum' },
  { match: 'Bijenkorf', category: 'shopping' },
  { match: 'BRUG 34', category: 'food' },
  { match: 'Hummbar', category: 'food' },
  { match: 'BURGERIJ', category: 'food' },
  { match: 'Grand Cafe de Balie', category: 'food' },
  { match: /cafe/i, category: 'food' },
  { match: 'VESTA PAYMENT SOLUTIONS', category: 'mobile' },
  { match: 'Buckaroo Stichting Derde', category: 'charity' },
  { match: 'Soup en Zo', category: 'food' },
  { match: 'Bar Moustache', category: 'food' },
  { match: 'Gollem', category: 'food' },
  { match: 'AMERICAN BOOK CENTER', category: 'books' },
  { match: 'Gasthuijs', category: 'food' },
  { match: 'La Place', category: 'food' },
  { match: 'OMELEGG', category: 'food' },
  { match: 'Paradiso', category: 'concerts' },
  { match: 'Ysbreker', category: 'food' },
  { match: /^Febo/, category: 'food' },
  { match: 'GlobalCollect', category: 'travel' },
  { match: 'Global Collect BV', category: 'travel' },
  { match: 'A Space Oddity', category: 'entertaiment' },
  { match: 'Stichting Derdengelden', category: 'sports' },
  { match: 'O mai Amsterdam', category: 'food' },
  { match: 'Venkel', category: 'food' },
  { match: 'Blos Horeca', category: 'food' },
  { match: 'OUDE ZIJDS HORECA', category: 'food' },
  { match: 'De Haven', category: 'food' },
  { match: 'McDonald', category: 'food' },
  { match: 'OPLADENOV', category: 'transport' },
  { match: 'MM Amsterdam Centrum', category: 'entertaiment' },
  { match: 'pizzeria', category: 'food' },
  { match: 'etos', category: 'home' },
  { match: 'Nassau', category: 'food' },
  { match: 'Stach', category: 'groceries' },
  { match: 'UTRECHTSESTRAAT 13', category: 'cash' },
  { match: 'Bever', category: 'clothes' },
  { match: 'STG ADYEN', category: 'travel' },
  { match: 'motel', category: 'travel' },
  { match: 'Happy italy', category: 'food' },
  { match: 'Volendammer Vishande', category: 'food' },
  { match: 'HEEREN', category: 'food' },
  { match: 'BK 13462', category: 'food', name: 'Burger King' },
  { match: 'TAVERNA BARCELONA', category: 'food' },
  { match: 'ING BANK', category: 'cash' },
  { match: 'JAN VAN GALENSTR 86', category: 'cash' },
  { match: 'Prime Cuts BV', category: 'food', note: 'burgers' },
  { match: 'Greenwoods', category: 'food' },
  { match: 'Frozz B.V', category: 'food' },
  { match: 'YOGEN FRUZ', category: 'food' },
  { match: 'Storm B.V. ZANDVOORT', category: 'food' },
  { match: 'DIESEL STORE', category: 'clothes' },
  { match: 'GREEN BUDGET BIKES', category: 'home' },
  { match: 'BELASTINGDIENST', category: 'services' },
  { match: 'EXPERCASH GmbH', category: 'tickets' },
  { match: 'HavenrestaurantTexel', category: 'food' },
  { match: 'Fietsverhuur', category: 'transport' },
  { match: 'Teddy`s Grill', category: 'food' },
  { match: 'Kruidvat', category: 'home' },
  { match: 'NEW YORK PIZZA', category: 'food' },
  { match: 'JODENBREESTRAAT 96', category: 'cash' },
  { match: 'ZUCCA LEIDEN', category: 'food' },
  { match: 'EAZIE', category: 'food' },
  { match: 'THE DUTCH CO', category: 'food' },
  { match: /BRASSERIE/i, category: 'food' },
  { match: /horeca/i, category: 'food' }, // https://en.wikipedia.org/wiki/Horeca
  { match: /RESTAURANT/i, category: 'food' },
  { match: 'Corner Admiraal', category: 'food', note: 'near' },
  { match: 'Rembr van gogh', category: 'museum' },
  { match: 'Zhu Lin VOF', category: 'food', name: 'Wannemakers!' },
  { match: 'ROEST', category: 'food' },
  { match: 'ING AMSTERDAM', category: 'cash' },
  { match: 'HMSHOST AMSTERDAM SCHI', category: 'food' },
  { match: 'SPARKASSE ERDING-DORFE', category: 'shit' },
  { match: 'Avondwinkel', category: 'groceries' },
  { match: 'Squash City', category: 'sports' },
  { match: 'BGN WEST BV', category: 'food', name: 'Cafe De Klos' }
];
